### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) : ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

### ISSUE THREAD

**Issue by RosebudAnwuri** [rstudio/kerasjs#2]
Hi there,

I keep getting an error whenever i call the keras_convertjs
`model_path <- system.file("my-path/keras_model.hdf5"
, package = "kerasjs")
kerasjs_convert(model_path)`
`#Error in normalizePath(path.expand(path), winslash, mustWork) : path[1]="": The filename, directory name or volume label syntax is incorrect`
How do I fix this?

**Comment by skeydan** [comment]
Hi,
when using one of your own saved models (not an example model that comes with the package) you should just use

`model_path <- "my_relative_path/myfile.hdf5"` (resp. `"/my_absolute_path/myfile.hdf5"`)

**Comment by RosebudAnwuri** [comment]
Thanks! I got another error however.

` Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr `

**Comment by javierluraschi** [comment]
@RosebudAnwuri should be fixed now, looks like we missed to do more testing in Windows. Try reinstalling with:

```
devtools::install_github("rstudio/kerasjs")
```
